Vagrant.configure("2") do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.synced_folder  "../", "/tmp/cupsc"

  config.vm.network :private_network, ip: "192.168.56.101"
    config.vm.network :forwarded_port, guest: 80, host: 8080
    config.ssh.forward_agent = true

  config.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--memory", 1024]
    v.customize ["modifyvm", :id, "--name", "cupsc"]
  end

  config.vm.provision :shell, :inline => 'mkdir /var/www'
  config.vm.provision :shell, :inline => 'rsync -rtC /tmp/cupsc /var/www/ --exclude=vagrant --exclude=.vagrant --exclude=.idea'
  config.vm.provision :shell, :inline => 'umount /tmp/cupsc && rm -rf /tmp/cupsc'
  config.vm.provision :shell, :inline => 'chown -R vagrant:vagrant /var/www/cupsc'
  config.vm.provision :shell, :inline => 'sudo setfacl -R -m u:www-data:rwX -m u:`whoami`:rwX app/cache app/logs'
  config.vm.provision :shell, :inline => 'sudo setfacl -dR -m u:www-data:rwX -m u:`whoami`:rwX app/cache app/logs'

  config.vm.provision :shell, :inline =>
    "if [[ ! -f /apt-get-run ]]; then sudo apt-get update && sudo touch /apt-get-run; fi"

  config.vm.provision :shell, :inline => 'echo -e "mysql_root_password=
    controluser_password=awesome" > /etc/phpmyadmin.facts;'

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "manifests"
    puppet.module_path = "modules"
    puppet.options = ['--verbose']
  end

end
